// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/7/2025, 6:17:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/kevinbarfleur/Github/LeCollecteurDeDose/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/components/card/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/components/ui/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/plugins/**/*.{js,ts,mjs}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/composables/**/*.{js,ts,mjs}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/utils/**/*.{js,ts,mjs}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kevinbarfleur/Github/LeCollecteurDeDose/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;